### PR TITLE
Pretty login forms

### PR DESCRIPTION
**Pull request by reginafcompton**
This PR updates the UI of the login and consent forms (according to new wireframes). 

@gregmundy - there's nothing particularly noteworthy code-wise. Tagging you as a friendly "fyi."

### Demo

secret

### CODE REVIEW

**Comment by gregmundy** [comment]
This branding doesn’t reflect the real need for authserver. Recall that Facet is redirecting to a login page owned by authserver. Any other client that uses authserver will also be redirected to this page. As such, the heading should reflect authserver and not Facet.

**Comment by reginafcompton** [comment]
@gregmundy - yes, we're aware of that distinction, and we discussed it at a previous Facet round up (namely, "how should we differentiate between the two services: Facet vs. Authserver?"). I think the goal with these wireframes is to make the login process as smooth as possible. Soooooo....some thoughts on your thoughts:

> Any other client that uses authserver will also be redirected to this page.

Is this a concern, at this point? I agree that other clients (not Facet) might use Authserver, but that's not something we can expect in the immediate future...right?

> the heading should reflect authserver and not Facet.

I can see two simple solutions: 

1. replace the word "facet" with "authserver" (upper right) and remove "powered by authserver" (lower left)

-OR-

2.  remove "facet" (upper right) and keep the "powered by authserver." 

Aside from that, I do not think we want to spend much time with authserver branding for the initial version of Facet + Authserver. 

What do you think, Greg? I'll ping Sarah and Vyki to get their input, too!

**Comment by gregmundy** [comment]
@reginafcompton PAIRIN will potentially be making use of Authserver in the not too distant future depending on some conversations we're working through with them. Either alternative that you propose is fine with me. I simply don't want to cause confusion with where the boundary between Facet and Authserver lies.

**Comment by srhhnry** [comment]
Hmmm, I really really dislike the idea of changing the screens too much. It breaks trust from the user perspective, and can be confusing. 

Is it possible to put this instance of authserver on a Facet-specific URL? Otherwise I like option 2 that Regina has proposed (removing Facet and keeping powered by authserver on the bottom) as it feels the least noticeable.

**Comment by reginafcompton** [comment]
Thanks, @srhhnry ! We'll go with option No. 2. Basically, we want to remove the word "Facet" from the authserver service (since as Greg notes above) PAIRIN might be integrating with authserver (_without_ Facet) in the foreseeable future.

**Comment by srhhnry** [comment]
Sounds good!

**Comment by reginafcompton** [comment]
@srhhnry @gregmundy - I implemented solution no. 2 above:

> remove "facet" (upper right) and keep the "powered by authserver."

We'll likely revisit this: (1) if/when a customer asks for data-trust-specific branding, or (2) if/when we renew our "interim" BrightHive branding with something else. For now....here it is:

Screen Shot 2019-11-18 at 10 33 26 AM

**Pull request merged**
